### ISSUE TITLE
Red square

### ISSUE THREAD

**Issue by maddmurdoc** [rsoesemann/plantuml4force#2]
1. We would like to be able to see the fields being populated to via apex classes or processes in the diagram. Is this possible?

In salesforce lingo what does the red square (protected) translate to?

**Comment by rsoesemann** [comment]
Not sure what you are asking. This is Open Source. Please check the simple code to find out what the when the red square is rendered. Regarding feature requests...everything is possible. For the repo and build it. If its good I will review it and merge it into the main repo.
