### ISSUE TITLE
SFDX deploy button returns error message for non-dev org

### ISSUE THREAD

**Issue by snugsfbay** [rsoesemann/plantuml4force#4]
> Sorry, something went wrong!
> 
> Please send a message to @WadeWegner for help.
> 
> If you work for Salesforce and it failed during login, it's likely the browser keeps trying to access your Org62 or GUS token (which won't work). Try a fresh browser.

**Comment by snugsfbay** [comment]
Downloaded the source, put it into VS Code, ran deploy to sourced org and got it to install just fine that way.

**Comment by rsoesemann** [comment]
I converted the repo to a namespace-less unlocked package with both source and metadata sources. It now can be installed on scratch and regular orgs.
