### ISSUE TITLE
GACK error when I add one more class to a complex diagram

### ISSUE THREAD

**Issue by snugsfbay** [rsoesemann/plantuml4force#5]
Salesforce System Error: 687522327-140971 (1199635390) (1199635390)
Error is in expression '{!doCreateDiagram}' in component <apex:commandButton> in page classdiagramcreator: Class.ApexParser.getCleaned: line 38, column 1
Class.ApexParser.parse: line 12, column 1
Class.ClassDiagramCreatorCtrl.doCreateDiagram: line 50, column 1

An unexpected error has occurred. Your development organization has been notified.

**Comment by snugsfbay** [comment]
Seems to be related to the specific class, which gets the system error even when I try to map it by itself.

**Comment by rsoesemann** [comment]
The parser uses regular expression and is not really robust. I guess I can’t do anything against that.

**Comment by rsoesemann** [comment]
@snugsfbay can you post the class which lead to this error? Maybe a stripped down version...
