### ISSUE TITLE
Promoting SFDX package version for Production use

### ISSUE THREAD

**Issue by Clint-Chester** [rsoesemann/plantuml4force#6]
Would love to be able to run with just using the package version you've provided rather than managing the same package in our own DevHub, but it's coming up that the current package version is still in beta. Would you be happy to promote the current package version so we are able to install in Production environments?

**Comment by rsoesemann** [comment]
You mean make it a released unlocked package? Why not let’s see if I have time in the next days. Stay tuned.

**Comment by rsoesemann** [comment]
I promoted package version 04t4A000000YXHFQA4 to released. Please check if it works now.

**Comment by Clint-Chester** [comment]
Perfect! Thanks @rsoesemann 😄
